# Generated by Django 4.2.30 on 2026-05-29 21:24

from django.db import migrations


REGIONS = [
    ("us-east", "US East"),
    ("us-west", "US West"),
]


def seed_regions(apps, schema_editor):
    Region = apps.get_model("shared_app", "Region")
    for code, name in REGIONS:
        Region.objects.get_or_create(code=code, defaults={"name": name})


def unseed_regions(apps, schema_editor):
    Region = apps.get_model("shared_app", "Region")
    Region.objects.filter(code__in=[code for code, _ in REGIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shared_app', '0002_region'),
    ]

    operations = [
        migrations.RunPython(seed_regions, unseed_regions),
    ]
