# Generated by Django 4.2.30 on 2026-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='region_id',
            field=models.CharField(default='us-east', max_length=50),
            preserve_default=False,
        ),
    ]
